name: Docs
on: [push, pull_request, workflow_dispatch]
permissions:
    contents: write
jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
      - name: Upgrade pip
        run: |
          python3 -m pip install --upgrade pip
      - name: Get pip cache dir
        id: pip-cache                
        run: echo "dir=$(pip cache dir)" >> $GITHUB_OUTPUT
      - name: set pythonpath
        run: |
          echo "::set-env name=PYTHONPATH::${{ github.workspace }}/determined"
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ${{ steps.pip-cache.outputs.dir }}
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Install dependencies from another repository
        run: |
          git clone https://github.com/determined-ai/determined.git
      - name: Install dependencies
        run: |
          pip install sphinx sphinx-book-theme
      - name: Sphinx build
        run: |
            sphinx-build source docs
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        with:
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
          force_orphan: true